eval:
    pattern: /espace-client/evaluation
    defaults: { _controller: "djepoLocationBundle:evaluation:index" }

eval_show:
    pattern:   /espace-client/evaluation/{id}/show
    defaults: { _controller: "djepoLocationBundle:evaluation:show" }
    
eval_showAppreciation:
    pattern:    /evaluation/logement/{id}
    defaults: { _controller: "djepoLocationBundle:evaluation:showAppreciation" }
eval_new:
    pattern:   /espace-client/evaluation/new
    defaults: { _controller: "djepoLocationBundle:evaluation:new" }

eval_create:
    pattern:   /espace-client/evaluation/create
    defaults: { _controller: "djepoLocationBundle:evaluation:create" }
    requirements: { _method: post }

eval_edit:
    pattern:    /espace-client/evaluation/{id}/edit
    defaults: { _controller: "djepoLocationBundle:evaluation:edit" }

eval_update:
    pattern:   /espace-client/evaluation/{id}/update
    defaults: { _controller: "djepoLocationBundle:evaluation:update" }
    requirements: { _method: post|put }

eval_delete:
    pattern:   /espace-client/evaluation/{id}/delete
    defaults: { _controller: "djepoLocationBundle:evaluation:delete" }
    requirements: { _method: post|delete }
