djepoImg:
    pattern:  /
    defaults: { _controller: "djepoLocationBundle:image:index" }

djepoImg_show:
    pattern:  /{id}/show
    defaults: { _controller: "djepoLocationBundle:image:show" }

djepoImg_new:
    pattern:  /new
    defaults: { _controller: "djepoLocationBundle:image:new" }

djepoImg_create:
    pattern:  /create
    defaults: { _controller: "djepoLocationBundle:image:create" }
    requirements: { _method: post }

djepoImg_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "djepoLocationBundle:image:edit" }

djepoImg_update:
    pattern:  /{id}/update
    defaults: { _controller: "djepoLocationBundle:image:update" }
    requirements: { _method: post|put }

djepoImg_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "djepoLocationBundle:image:delete" }
    requirements: { _method: post|delete }
