<?php

namespace djepo\calandarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * calandarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventEntityRepository extends EntityRepository
{
}