<?php

namespace djepo\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * imageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageRepository extends EntityRepository
{
    public function recupReqAll($data) 
	{
	     switch($data)
          {
	        case 'seflModel' :
	             $sql= 'SELECT * FROM images WHERE photo1<>"" ORDER BY num DESC';
			
			    break;
		}
			$this->selectAll= Controller_Template::$db->prepare($sql);
			//return $this->selectById;
    }
	
	
	public function deleteReqbyId($data) 
	{
	     switch($data)
          {
	        case 'seflModel' :
	             $sql= 'DELETE FROM images WHERE NUM = ?' ;
			
			    break;
		}
			$this->deleteById= Controller_Template::$db->prepare($sql);
			
    }
	
	
	
	public function recupReqbyId($data) 
	{
	     switch($data)
          {
	        case 'seflModel' :
	             $sql= 'SELECT * FROM images WHERE num = ?';
			
			    break;
		  }
			$this->selectById= Controller_Template::$db->prepare($sql);
			
    }
	
	public function recupReqUpdate($type) 
	{
	
	  switch($type)
          {
		  
		    case 'seflModel':
			    $sql='INSERT INTO images(comment1) VALUES(?)';
				
			break;
			
			case 'upModel1':
			    $sql='UPDATE images SET photo1= ? WHERE num = ?';
				
			break;
			
			case 'upModel2':
			    $sql='UPDATE images SET picto1= ? WHERE num = ?';
				break;
				
			case 'upModel3':
			    $sql='UPDATE images SET comment1= ? WHERE num = ?';	
				
			break;
			
			case 'upLocation':
			    $sql='UPDATE images  SET photo1 = ? ,
				                      photo2 = ?,
                                      idLogement = ?							 
				     WHERE num = ?';
				
			break;
	
	      }		    
			 $this->updateById= Controller_Template::$db->prepare($sql);
			  
	 }
}
