<?php

namespace djepo\LocationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * locationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class locationRepository extends EntityRepository
{
    public function calandar($startDate, $id ) {
            $qb=$this->createQueryBuilder('l');
            $qb->where('l.logement = :logement')->setParameter('logement', $id);
            $qb = $this->whereCalandarValide( $qb);
            $qb = $this->whereCalandarDate( $qb, $startDate  );
           // $qb = $this->whereCalandarOrder( $qb);
            $qb->getQuery()->getResult();
            return $qb;
        }
        public function whereCalandarValide(\Doctrine\ORM\QueryBuilder $qb )
        {
                $qb->andWhere('l.valide = :valide')->setParameter('valide', '1') ;
                 return $qb;
        }
        
        public function whereCalandarDate(\Doctrine\ORM\QueryBuilder $qb, $startDate)
        { 
                $qb->andWhere('l.dateLocation < :startDate')
                //->orWhere('l.dateFinLocation < :startDate')
                ->setParameter('startDate', $startDate); //->format('Y-m-d')
                 return $qb;
        }
        
        public function whereCalandarOrder(\Doctrine\ORM\QueryBuilder $qb )
        {
                $qb->orderBy('l.dateLocation','DESC');
              
                 return $qb;
        }
}
